import '../styles/globals.css';
import '../styles/variables.css';
import '../styles/media.css';
import {Inter} from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Nastja Crochets',
    description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <body className={inter.className} id="root">{children}</body>
    </html>
  );
}
